#!/bin/sh
xrdb -merge $HOME/.Xresources &

pgrep -x sxhkd > /dev/null || sxhkd &

dunst -conf $HOME/.config/dunst/dunstrc > /dev/null 2>&1 &
nitrogen --restore &

$HOME/.config/polybar/launch.sh

bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor DP3 -d 6 7 8 9 0

bspc config border_width         1
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a discord desktop='1'
bspc rule -a Google-chrome desktop='2'
bspc rule -a Alacritty desktop='3' follow=on
bspc rule -a Spotify desktop='6'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Dunst layer='above'
bspc rule -a Mirage state=floating
bspc rule -a dropdown sticky=on state=floating hidden=on

# kitty --class dropdown &
