#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
dunst -conf $HOME/.config/dunst/dunstrc > /dev/null 2>&1 &

$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a discord desktop='^1'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Google-chrome desktop='^2'
bspc rule -a Alacritty desktop='^3' follow=on
bspc rule -a Spotify desktop='^6'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Dunst layer='above'
