#!/usr/bin/python

from sys import argv

if __name__ == "__main__":
    try:
        time = argv[1]
        hour, minute = time.split(":")
        minute = int(minute) * 10/6

        print("{}.{}".format(hour, minute))
    except Exception:
        print("Time format needs to be hh:mm")
        exit(1)
