#!/usr/bin/python

from sys import argv

if __name__ == "__main__":
    time = argv[1]
    hour, minute = time.split(":")
    total_minutes = int(hour) * 60 + int(minute)

    converted_time = total_minutes / 60.0

    print(converted_time)
