# Autocompletion enabled
fpath+=~/.config/zsh/completions
autoload -Uz compinit
compinit -u

# History
HISTFILE=$HOME/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

# ENV
CUSTOM_SCRIPTS=$HOME/.config/custom_scripts
LOCAL_SCRIPTS=$HOME/.localscripts
LOCAL_BIN=$HOME/.local/bin

export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -f -U -g ""'

export GOPATH=$HOME/go-workspace
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:$GOPATH/bin:$GOROOT/bin
export PATH=$LOCAL_BIN:$PATH:$CUSTOM_SCRIPTS:$LOCAL_SCRIPTS
export PROXY_URL="http://198.161.14.25:8080"

# Vim Wiki extensions
export VIMWIKI_MARKDOWN_EXTENSIONS="toc,fenced_code,codehilite"

## Theme
# export PS1="%d %% "

export ZSH_THEME_DIR="$HOME/.config/zsh/themes"
source $ZSH_THEME_DIR/ale-zsh/ale.zsh-theme;

## Bindings
bindkey "^[[1~" beginning-of-line
bindkey "^[[4~" end-of-line
bindkey "^[[3~" delete-char
bindkey "^[^[[C" end-of-line
bindkey "^[^[[D" beginning-of-line
# Vim Home/End
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line
# Alt arrow
bindkey "^[[1;3C" end-of-line
bindkey "^[[1;3D" beginning-of-line 

## Aliases

alias prompt-pwd=pwd
alias v=nvim
alias zshconfig="nvim $HOME/.zshrc"
alias zshreload="source $HOME/.zshrc"
alias ls=exa
# alias open=xdg-open
alias urestart="sudo systemctl restart urxvtd@lucas"
alias ustop="sudo systemctl stop urxvtd@lucas"
alias xrreload="xrdb ~/.Xdefaults"
alias setkb="setxkbmap"
alias pipclean="pip freeze | xargs pip uninstall -y"
alias battery-status="upower -i /org/freedesktop/UPower/devices/battery_BAT0"
alias sed=gsed
alias showtemp="sudo powermetrics --samplers smc"
alias nuw="npm run unit:watch"
alias nr="npm run"


## Inits

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

## Completions

# Enable menu select completion
zstyle ':completion:*' menu select

## Plugins
export ZSH_PLUGIN_DIR="$HOME/.config/zsh/plugins"

# Syntax highlight
source $ZSH_PLUGIN_DIR/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh;

# Copy-paste
source $ZSH_PLUGIN_DIR/copy-pasta/copy-pasta.plugin.zsh;

# fzf-tab
source $ZSH_PLUGIN_DIR/fzf-tab/fzf-tab.plugin.zsh;

# git aliases
source $ZSH_PLUGIN_DIR/oh-my-git-aliases/oh-my-git-aliases.sh;

# hacker quote
source $ZSH_PLUGIN_DIR/hacker-quotes/hacker-quotes.plugin.zsh;

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# direnv
eval "$(direnv hook zsh)"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# gcloud
if [ -f '~/google-cloud-sdk/path.zsh.inc' ]; then . '~/google-cloud-sdk/path.zsh.inc'; fi
if [ -f '~/google-cloud-sdk/completion.zsh.inc' ]; then . '~/google-cloud-sdk/completion.zsh.inc'; fi
